kind: Deployment
apiversion: apps/v1
metadata:
   name: mydeployment
spec:
  replicas: 2
  selector:
     matchlabels:
        app: myspringbootapp
  template:
    metadata:
      labels:
        app: myspringbootapp
    spec:
      containers:
        - name: myspringbootapp
          image: gopidevopskanna/demo-counter-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9099
